### ISSUE TITLE
Error when running createHTML.py script

### ISSUE THREAD

**Issue by AndreaAguadoM** [TKSjp/HaplotypeExplorer#1]
Hello, my name is Andrea. 
I am trying to use the HaplotypeExplorer tool in order to study some quasispecies sequences that proceed from the same sample. Specifically, I am trying to run this script with a multifasta file containing these quasispecies' sequences as input, as it follows: 
python createHTML.py, within a directory where the input.fasta is contained. At the same time, within the Source directory, I have placed the reference.fasta file that I want to use, but I do obtain the following errors: 

ERROR: Alignment not loaded: "input.mafft.fasta" Check the file's content.

and then later: 

Fatal Error:
Failed to open the database file
Program halted !!

I've been checking the different files this tool creates, and for example, input2.fasta remains empty after the program gets killed. I think I am trying to run Haplotype Explorer in the wrong way. Could someone help me?

Thanks in advance!

**Comment by TKSjp** [comment]
Hi

> ERROR: Alignment not loaded: "input.mafft.fasta" Check the file's content.

This indicates trimal could not load the alignment data generated by mafft (input.mafft.fasta), which is from input2.fasta.
The input2.fasta is multi-fasta file automatically generated by the seqkit and sed. So there may be problem in running sed or seqkit. 

Would you check whether sed and seqkit correctly executed?

Thanks
